version: '3.7'

services:
  web:
    build: ./app
    command: >
      sh -c "python manage.py migrate &&
             gunicorn calculator_logs.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web